### PR TITLE
implement sqrtf

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ce8fa49 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ce8fa49 with merge ce8fa49...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/m/build/1.0.8)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d1bc4e5 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d1bc4e5 with merge d1bc4e5...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/m/build/1.0.9)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 64661b8 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 64661b8 with merge 64661b8...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/m/build/1.0.10)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 689a1e0 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 689a1e0 with merge 689a1e0...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/m/build/1.0.11)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f7d2a00 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f7d2a00 with merge f7d2a00...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/m/build/1.0.12), [status-travis](https://travis-ci.org/japaric/m/builds/169125467)
Approved by: japaric
Pushing f7d2a0048a0fbef6aa35a0717673d9b74c3743ec to master...

**Pull request merged**
