### PR TITLE
.travis: remove the webhooks

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 3e12d16 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 3e12d16 with merge 3e12d16...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9681af7 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9681af7 with merge 9681af7...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/m/build/1.0.14), [status-travis](https://travis-ci.org/japaric/m/builds/174109670)
Approved by: japaric
Pushing 9681af7daab5743d75de4acbbd0ae7772efa98c4 to master...

**Pull request merged**
