### PR TITLE
add CI infrastructure

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 38d63f4 with merge 38d63f4...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/m/build/1.0.1)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 09379db has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 09379db with merge 09379db...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-appveyor](https://ci.appveyor.com/project/japaric/m/build/1.0.2)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8b0050d has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8b0050d with merge 8b0050d...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 33eb8da has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 33eb8da with merge 33eb8da...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/m/builds/167896077)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9a86eed has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9a86eed with merge 9a86eed...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/m/build/1.0.5), [status-travis](https://travis-ci.org/japaric/m/builds/167898711)
Approved by: japaric
Pushing 9a86eed1ffdcafa85aee641326ce0b140c2e60c1 to master...

**Pull request merged**
