### PR TITLE
update docs and cargo fmt

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 88831d5 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 88831d5 with merge 88831d5...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/m/build/1.0.6), [status-travis](https://travis-ci.org/japaric/m/builds/167906104)
Approved by: japaric
Pushing 88831d52142e60069ba81d013d3be58e66742630 to master...

**Pull request merged**
