### PR TITLE
use cross to simplify CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e37cb74 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e37cb74 with merge e37cb74...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 6abe7cf has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6abe7cf with merge 6abe7cf...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/m/build/1.0.16), [status-travis](https://travis-ci.org/japaric/m/builds/187369694)
Approved by: japaric
Pushing 6abe7cff49c7fd99de17b7f3c8aed106eeb02303 to master...

**Pull request merged**
