### PR TITLE
fix clippy warnings

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 6575c8c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6575c8c with merge 6575c8c...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-appveyor](https://ci.appveyor.com/project/japaric/m/build/1.0.7), [status-travis](https://travis-ci.org/japaric/m/builds/167912466)
Approved by: japaric
Pushing 6575c8c043e44997b875fb2375ddb813d258a610 to master...

**Pull request merged**
